workflows:
  ios-release:
    name: iOS Release (TestFlight)
    max_build_duration: 60
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: Furrow ASC API Key

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true

    scripts:
      - name: Install dependencies
        script: flutter pub get

      - name: Install CocoaPods
        script: cd ios && pod install

      - name: Set up code signing
        script: xcode-project use-profiles

      - name: Build IPA
        script: |
          flutter build ipa \
            --release \
            --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        expire_build_submitted_for_review: true
      email:
        recipients:
          - noreply@furrow.app  # Replace with your email
        notify:
          success: true
          failure: true
